# Android Toolkit Configuration (permissions/compilation hints)
# [permission]
# package.name=dump,write,doze
# [compilation]
# package.name=PRIORITY_INTERACTIVE_FAST:speed-profile

[permission]
com.pittvandewitt.wavelet = "dump,write"
com.termux = "write,dump,doze"
moe.shizuku.privileged.api = "write"

[compilation]
com.android.chrome = "PRIORITY_INTERACTIVE_FAST:speed-profile"
com.android.systemui = "PRIORITY_FOREGROUND:speed"
com.google.android.gms = "PRIORITY_BACKGROUND:verify"
