# Taplo TOML formatter configuration
# https://taplo.tamasfe.dev/configuration/

[formatting]
align_entries = false
align_comments = true
array_trailing_comma = true
array_auto_expand = true
array_auto_collapse = true
compact_arrays = true
compact_inline_tables = false
column_width = 120
indent_tables = false
indent_entries = false
inline_table_expand = true
reorder_keys = false
reorder_arrays = false
allowed_blank_lines = 1
trailing_newline = true
crlf = false

[[rule]]
include = ["*.toml"]

[[rule]]
include = ["Cargo.toml"]
keys = ["dependencies", "dev-dependencies", "build-dependencies"]
formatting = { reorder_keys = true }
