# This configuration is used by https://qlty.sh
config_version = "0"
exclude_patterns = [
  "*_min.*",
  "*-min.*",
  "*.min.*",
  "**/.yarn/**",
  "**/*.d.ts",
  "**/assets/**",
  "**/bower_components/**",
  "**/build/**",
  "**/cache/**",
  "**/config/**",
  "**/db/**",
  "**/deps/**",
  "**/dist/**",
  "**/extern/**",
  "**/external/**",
  "**/generated/**",
  "**/Godeps/**",
  "**/gradlew/**",
  "**/mvnw/**",
  "**/node_modules/**",
  "**/protos/**",
  "**/seed/**",
  "**/target/**",
  "**/templates/**",
  "**/testdata/**",
  "**/vendor/**",
]
test_patterns = [
  "**/test/**",
  "**/spec/**",
  "**/*.test.*",
  "**/*.spec.*",
  "**/*_test.*",
  "**/*_spec.*",
  "**/test_*.*",
  "**/spec_*.*",
]

[smells]
mode = "comment"

[[source]]
name = "default"
default = true

[[plugin]]
name = "actionlint"

[[plugin]]
name = "ast-grep"

[[plugin]]
name = "biome"

[[plugin]]
name = "eslint"

[[plugin]]
name = "bandit"

[[plugin]]
name = "radarlint-python"
mode = "comment"

[[plugin]]
name = "ripgrep"
mode = "comment"

[[plugin]]
name = "ruff"
drivers = [
  "lint",
]

[[plugin]]
name = "black"

[[plugin]]
name = "shellcheck"

[[plugin]]
name = "trivy"
drivers = [
  "config",
]

[[plugin]]
name = "trufflehog"

[[plugin]]
name = "prettier"

[[plugin]]
name = "yamllint"

[[plugin]]
name = "markdownlint"
