name: Shell Lint & Format
on: 
  workflow_dispatch:
  pull_request:
    paths:
      - "**/*.{sh,bash,bashrc,profile}"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions: 
  contents: write
  pull-requests: write
env:
  DEBIAN_FRONTEND: noninteractive
  LC_ALL: C
  GITHUB_TOKEN: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}
  SHELLCHECK_OPTS: "--source-path=SCRIPTDIR --external-sources --check-sourced --severity=style --shell=bash"

jobs:
  lint:
    strategy:
      matrix:
        shell: [bash, sh]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with: 
          fetch-depth: 0
      - name: Install tools
        run: |
          sudo apt-get update -y; sudo apt-get install -y shellcheck shfmt
          curl -sfL https://github.com/anordal/shellharden/releases/latest/download/shellharden-x86_64-unknown-linux-musl.tar.gz | tar xz
          sudo mv shellharden /usr/local/bin/
      - name: Find & fix shell files
        shell: bash
        run: |
          while IFS= read -r f; do
            sed -i 's/() {/(){/g' "$f"; sed -i 's/|| true/|| :/g' "$f"
            sed -i '/^#[[:space:]]*-\{5,\}/d' "$f"; sed -i '/^$/{N;/^\n$/D;}' "$f"
            shellharden --replace "$f" &>/dev/null || :
            shellcheck -f diff --shell=${{ matrix.shell }} "$f" | patch -Np1 2>/dev/null || :
            shfmt -i 2 -s -bn -ln bash -w "$f" &>/dev/null || :
          done < <(
            {
              find -O2 . -type f \( -name '*.sh' -o -name '*.bash' -o -name '.bashrc'\) -print 2>/dev/null || :
              find -O2 . -type f -exec grep -Il '^#!/.*sh' {} + 2>/dev/null || :
            } | sort -u 2>/dev/null
          )
      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"; git config user.email "github-actions[bot]@users.noreply.github.com"
          git diff --quiet || { git add -A; git commit -m "ðŸ”§ Auto-fix shell scripts" && git push; }
